backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SearchController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use frontend\models\forms\SearchForm;

class SearchController extends Controller{

  public function actionIndex()
  {
    $model = new SearchForm();

    $results = null;

    if ($model->load(Yii::$app->request->post())) {
      $results = $model->search();
    }

    return $this->render('index', [
      'model' => $model,
      'results' => $results,
    ]);
  }

  public function actionAdvanced()
  {
    $model = new SearchForm();

    $results = null;

    if ($model->load(Yii::$app->request->post())) {
      $results = $model->searchAdvanced();
    }

    return $this->render('advanced', [
      'model' => $model,
      'results' => $results,
    ]);
  }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

frontend/controllers/TestController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use frontend\models\Test;
use frontend\models\example\ExampleValidation;
use Faker\Factory;

class TestController extends Controller
{
  public function actionIndex()
  {
    $max = Yii::$app->params['maxNewsInList'];

    $list = Test::getNewsList($max);

    return $this->render('index', [
      'list' => $list,
    ]);
  }

  public function actionView($id)
  {
    $item = Test::getItem($id);

    return $this->render('view', [
      'item' => $item
    ]);
  }

  public function actionMail()
  {
    $result = Yii::$app->mailer->compose()
      ->setFrom('rus.21region@gmail.com')
      ->setTo('rus-21region@mail.ru')
      ->setSubject('Тема сообщения')
      ->setTextBody('Текст сообщения')
      ->setHtmlBody('<b>текст сообщения в формате HTML</b>')
      ->send();

    var_dump($result);
    die;
  }

  public function actionValidation()
  {
    $model = new ExampleValidation();

    $formData = Yii::$app->request->post();

    if (Yii::$app->request->isPost) {
      $model->attributes = $formData;

      if ($model->validate()) {
        Yii::$app->session->setFlash('success', 'Data validated!');
      }
    }

    return $this->render('validation', [
      'model' => $model,
    ]);
  }

  public function actionGenerate()
  {
    ini_set('max_execution_time', 10000);

    /* @var $faker Faker\Generator */
    $faker = Factory::create();

    for ($j = 0; $j < 100; $j++) {

        $news = [];
        for ($i = 0; $i < 500; $i++) {
            $news[] = [$faker->text(35), $faker->text(rand(1000, 2000)), rand(0, 1)];
        }
        Yii::$app->db->createCommand()->batchInsert('news', ['title', 'content', 'status'], $news)->execute();
        unset($news);

    }

    die('stop');
  }

  public function actionSend()
    {
      if (!Yii::$app->user->isGuest) {
        if (Yii::$app->request->isPost) {
          $receiver = Yii::$app->request->post('receiver');
          $amount = Yii::$app->request->post('amount');
          // Logic
          echo "$amount$ sent to user $receiver";
          die;
        }
        return $this->render('send');
      }
      return $this->goHome();
    }
}

frontend/controllers/WindowController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use frontend\models\Window;

class WindowController extends Controller
{

  public function actionOrder()
  {
    $model = new Window();

    $formData = Yii::$app->request->post();

    if (Yii::$app->request->isPost) {
      $model->attributes = $formData;

      if ($model->validate() && $model->send($formData)) {
        Yii::$app->session->setFlash('success', 'Ordered!');
      }
    }

    return $this->render('order', [
      'model' => $model,
    ]);
  }

}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
use frontend\widgets\newsList\NewsList;
?>
<div class="site-about">
    <div class="row">
        <div class="col-md-9">
            <h1><?= Html::encode($this->title) ?></h1>

            <p>This is the About page. You may modify the following file to customize its content:</p>

            <code><?= __FILE__ ?></code>
        </div>
        <div class="col-md-3">
            <?php echo NewsList::widget(['showLimit' => 3]); ?>
        </div>
    </div>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
use frontend\widgets\newsList\NewsList;

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        Hello, <?php if (Yii::$app->user->identity) echo Yii::$app->user->identity->username; ?>
        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="<?php echo Url::to(['newsletter/subscribe']); ?>">Subscribe to newsletter</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-3">
                <h2>Заказать окно</h2>

                <p>Заказывайте наши окна! Нажми на кнопку ниже и закажите. Все просто!</p>

                <p><a class="btn btn-default" href="<?php echo Url::to(['window/order']); ?>">Заказать окно</a></p>
            </div>
            <div class="col-lg-3">
                <h2>Heading</h2>

                <?php echo NewsList::widget(['showLimit' => 2]); ?>
            </div>
            <div class="col-lg-3">
                <h2>Money</h2>
                <p><a class="btn btn-default" href="<?php echo Url::to(['test/send']); ?>">Send money</a></p>
            </div>
            <div class="col-lg-3">
                <h2>Heading</h2>

                <a href="<?php echo Url::to(['search/index']); ?>">Search v2</a>
                <br/>
                <a href="<?php echo Url::to(['search/advanced']); ?>">Search v3</a>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>